# Generated by Django 3.2.9 on 2022-09-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCodeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(default='', max_length=255, verbose_name='IP')),
                ('code', models.IntegerField(default=0, verbose_name='验证码')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮箱验证码session',
                'verbose_name_plural': '邮箱验证码session',
            },
        ),
    ]
