# Generated by Django 3.2.9 on 2022-10-09 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_emailcodesession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailcodesession',
            options={'verbose_name': '邮箱验证码Session', 'verbose_name_plural': '邮箱验证码Session'},
        ),
        migrations.RenameField(
            model_name='emailcodesession',
            old_name='ip',
            new_name='username',
        ),
    ]
