# Generated by Django 3.2.9 on 2022-10-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0007_alter_emailcodesession_create_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloudPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, upload_to='static/media')),
            ],
        ),
    ]
