# Generated by Django 3.2.9 on 2022-10-20 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0009_alter_emailcodesession_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcodesession',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='账号'),
        ),
    ]
