# Generated by Django 3.2.9 on 2022-09-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem', models.CharField(default='', max_length=255, verbose_name='梗')),
                ('pinyin', models.CharField(default='', max_length=255, verbose_name='拼音')),
                ('english', models.CharField(default='', max_length=255, verbose_name='英文名')),
                ('year', models.IntegerField(default=0, verbose_name='年份')),
                ('come_from', models.TextField(default='', verbose_name='出处')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('hot', models.IntegerField(default=0, verbose_name='热度')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
