# Generated by Django 3.2.9 on 2022-09-10 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stem',
            options={'verbose_name': '梗', 'verbose_name_plural': '梗'},
        ),
        migrations.CreateModel(
            name='StemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stem.stem')),
            ],
            options={
                'verbose_name': '吐槽',
                'verbose_name_plural': '吐槽',
            },
        ),
    ]
