# Generated by Django 3.2.9 on 2022-09-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0002_auto_20220910_1012'),
    ]

    operations = [
        migrations.CreateModel(
            name='StemRecommend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('today', models.CharField(default='', max_length=255, verbose_name='日期')),
                ('stem_id', models.CharField(default='', max_length=255, verbose_name='梗id')),
                ('stem', models.CharField(default='', max_length=255, verbose_name='梗')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '今日推荐',
                'verbose_name_plural': '今日推荐',
            },
        ),
    ]
