# Generated by Django 3.2.9 on 2022-09-10 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0003_stemrecommend'),
    ]

    operations = [
        migrations.CreateModel(
            name='StemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stemImage', models.CharField(default='', max_length=255, verbose_name='梗图')),
                ('stem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stem.stem')),
            ],
            options={
                'verbose_name': '梗图',
                'verbose_name_plural': '梗图',
            },
        ),
    ]
