# Generated by Django 3.2.9 on 2022-09-11 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0005_stemimage_create_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stemimage',
            old_name='stemImage',
            new_name='stem_image',
        ),
    ]
