# Generated by Django 3.2.9 on 2022-09-18 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0006_rename_stemimage_stemimage_stem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StemCommentReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=255, verbose_name='用户名')),
                ('content', models.TextField(default='', verbose_name='内容')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('stem_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stem.stemcomment')),
            ],
            options={
                'verbose_name': '吐槽回复',
                'verbose_name_plural': '吐槽回复',
            },
        ),
    ]
