# Generated by Django 3.2.9 on 2022-09-18 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0007_stemcommentreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='stemcommentreply',
            name='agree',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AddField(
            model_name='stemcommentreply',
            name='disagree',
            field=models.IntegerField(default=0, verbose_name='反对'),
        ),
    ]
