# Generated by Django 3.2.9 on 2022-09-19 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0008_auto_20220918_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='stemcomment',
            name='agree',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
        migrations.AddField(
            model_name='stemcomment',
            name='disagree',
            field=models.IntegerField(default=0, verbose_name='反对'),
        ),
    ]
