# Generated by Django 3.2.9 on 2022-10-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0009_auto_20220919_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='stemcomment',
            name='nickname',
            field=models.CharField(default='', max_length=255, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='stemcomment',
            name='username',
            field=models.CharField(default='', max_length=255, verbose_name='账号'),
        ),
    ]
