# Generated by Django 3.2.9 on 2022-10-12 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0010_auto_20221011_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stemcomment',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
