# Generated by Django 3.2.9 on 2022-10-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0011_alter_stemcomment_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stem',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stemcommentreply',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='stemimage',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
