# Generated by Django 3.2.9 on 2022-10-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0013_alter_stemrecommend_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stemimage',
            name='stem_image',
            field=models.ImageField(default='', max_length=255, upload_to='static/stem_image', verbose_name='梗图'),
        ),
    ]
