# Generated by Django 3.2.9 on 2022-10-22 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0014_alter_stemimage_stem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='StemSearchTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem_id', models.CharField(default='', max_length=255, verbose_name='梗id')),
                ('search_times', models.IntegerField(default=0, verbose_name='搜索次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '梗搜索次数统计',
                'verbose_name_plural': '梗搜索次数统计',
            },
        ),
    ]
