# Generated by Django 3.2.9 on 2022-11-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0019_delete_userstemsave'),
    ]

    operations = [
        migrations.CreateModel(
            name='StemUserCreate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stem_id', models.CharField(default='', max_length=255, verbose_name='梗id')),
                ('username', models.CharField(default='123456', max_length=255, verbose_name='用户名')),
            ],
            options={
                'verbose_name': '用户创作梗统计',
                'verbose_name_plural': '用户创作梗统计',
            },
        ),
    ]
