# Generated by Django 3.2.9 on 2022-11-26 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stem', '0020_stemusercreate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StemUserCreate',
        ),
    ]
