# Generated by Django 3.2.9 on 2022-09-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0002_user_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=255, verbose_name='邮箱'),
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='HelloWorld', max_length=255, verbose_name='昵称'),
        ),
    ]
