# Generated by Django 3.2.9 on 2022-10-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0004_user_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='num_comment',
            field=models.CharField(default=0, max_length=255, verbose_name='评论量'),
        ),
        migrations.AddField(
            model_name='user',
            name='num_views',
            field=models.CharField(default=0, max_length=255, verbose_name='浏览量'),
        ),
    ]
