# Generated by Django 3.2.9 on 2022-10-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0006_alter_user_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_image',
            field=models.ImageField(default='', max_length=255, upload_to='static/avatar', verbose_name='用户头像'),
        ),
    ]
