INSERT INTO `auth_permission` VALUES (1, 'Can add log entry', 1, 'add_logentry');
INSERT INTO `auth_permission` VALUES (2, 'Can change log entry', 1, 'change_logentry');
INSERT INTO `auth_permission` VALUES (3, 'Can delete log entry', 1, 'delete_logentry');
INSERT INTO `auth_permission` VALUES (4, 'Can view log entry', 1, 'view_logentry');
INSERT INTO `auth_permission` VALUES (5, 'Can add permission', 2, 'add_permission');
INSERT INTO `auth_permission` VALUES (6, 'Can change permission', 2, 'change_permission');
INSERT INTO `auth_permission` VALUES (7, 'Can delete permission', 2, 'delete_permission');
INSERT INTO `auth_permission` VALUES (8, 'Can view permission', 2, 'view_permission');
INSERT INTO `auth_permission` VALUES (9, 'Can add group', 3, 'add_group');
INSERT INTO `auth_permission` VALUES (10, 'Can change group', 3, 'change_group');
INSERT INTO `auth_permission` VALUES (11, 'Can delete group', 3, 'delete_group');
INSERT INTO `auth_permission` VALUES (12, 'Can view group', 3, 'view_group');
INSERT INTO `auth_permission` VALUES (13, 'Can add user', 4, 'add_user');
INSERT INTO `auth_permission` VALUES (14, 'Can change user', 4, 'change_user');
INSERT INTO `auth_permission` VALUES (15, 'Can delete user', 4, 'delete_user');
INSERT INTO `auth_permission` VALUES (16, 'Can view user', 4, 'view_user');
INSERT INTO `auth_permission` VALUES (17, 'Can add content type', 5, 'add_contenttype');
INSERT INTO `auth_permission` VALUES (18, 'Can change content type', 5, 'change_contenttype');
INSERT INTO `auth_permission` VALUES (19, 'Can delete content type', 5, 'delete_contenttype');
INSERT INTO `auth_permission` VALUES (20, 'Can view content type', 5, 'view_contenttype');
INSERT INTO `auth_permission` VALUES (21, 'Can add session', 6, 'add_session');
INSERT INTO `auth_permission` VALUES (22, 'Can change session', 6, 'change_session');
INSERT INTO `auth_permission` VALUES (23, 'Can delete session', 6, 'delete_session');
INSERT INTO `auth_permission` VALUES (24, 'Can view session', 6, 'view_session');
INSERT INTO `auth_permission` VALUES (25, 'Can add 梗', 7, 'add_stem');
INSERT INTO `auth_permission` VALUES (26, 'Can change 梗', 7, 'change_stem');
INSERT INTO `auth_permission` VALUES (27, 'Can delete 梗', 7, 'delete_stem');
INSERT INTO `auth_permission` VALUES (28, 'Can view 梗', 7, 'view_stem');
INSERT INTO `auth_permission` VALUES (29, 'Can add 吐槽', 8, 'add_stemcomment');
INSERT INTO `auth_permission` VALUES (30, 'Can change 吐槽', 8, 'change_stemcomment');
INSERT INTO `auth_permission` VALUES (31, 'Can delete 吐槽', 8, 'delete_stemcomment');
INSERT INTO `auth_permission` VALUES (32, 'Can view 吐槽', 8, 'view_stemcomment');
INSERT INTO `auth_permission` VALUES (33, 'Can add 今日推荐', 9, 'add_stemrecommend');
INSERT INTO `auth_permission` VALUES (34, 'Can change 今日推荐', 9, 'change_stemrecommend');
INSERT INTO `auth_permission` VALUES (35, 'Can delete 今日推荐', 9, 'delete_stemrecommend');
INSERT INTO `auth_permission` VALUES (36, 'Can view 今日推荐', 9, 'view_stemrecommend');
INSERT INTO `auth_permission` VALUES (37, 'Can add 梗图', 10, 'add_stemimage');
INSERT INTO `auth_permission` VALUES (38, 'Can change 梗图', 10, 'change_stemimage');
INSERT INTO `auth_permission` VALUES (39, 'Can delete 梗图', 10, 'delete_stemimage');
INSERT INTO `auth_permission` VALUES (40, 'Can view 梗图', 10, 'view_stemimage');
INSERT INTO `auth_permission` VALUES (41, 'Can add 吐槽回复', 11, 'add_stemcommentreply');
INSERT INTO `auth_permission` VALUES (42, 'Can change 吐槽回复', 11, 'change_stemcommentreply');
INSERT INTO `auth_permission` VALUES (43, 'Can delete 吐槽回复', 11, 'delete_stemcommentreply');
INSERT INTO `auth_permission` VALUES (44, 'Can view 吐槽回复', 11, 'view_stemcommentreply');
INSERT INTO `auth_permission` VALUES (45, 'Can add 梗搜索次数统计', 12, 'add_stemsearchtimes');
INSERT INTO `auth_permission` VALUES (46, 'Can change 梗搜索次数统计', 12, 'change_stemsearchtimes');
INSERT INTO `auth_permission` VALUES (47, 'Can delete 梗搜索次数统计', 12, 'delete_stemsearchtimes');
INSERT INTO `auth_permission` VALUES (48, 'Can view 梗搜索次数统计', 12, 'view_stemsearchtimes');
INSERT INTO `auth_permission` VALUES (49, 'Can add 用户', 13, 'add_user');
INSERT INTO `auth_permission` VALUES (50, 'Can change 用户', 13, 'change_user');
INSERT INTO `auth_permission` VALUES (51, 'Can delete 用户', 13, 'delete_user');
INSERT INTO `auth_permission` VALUES (52, 'Can view 用户', 13, 'view_user');
INSERT INTO `auth_permission` VALUES (53, 'Can add captcha store', 14, 'add_captchastore');
INSERT INTO `auth_permission` VALUES (54, 'Can change captcha store', 14, 'change_captchastore');
INSERT INTO `auth_permission` VALUES (55, 'Can delete captcha store', 14, 'delete_captchastore');
INSERT INTO `auth_permission` VALUES (56, 'Can view captcha store', 14, 'view_captchastore');
